# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('asctime', models.DateTimeField(null=True)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
