# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('photo_main', models.ImageField(upload_to=b'')),
                ('photo_big', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('user', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '\u041a\u0432\u0456\u0442\u043a\u0430',
                'verbose_name_plural': '\u041a\u0432\u0456\u0442\u0438',
            },
        ),
    ]
